# Generated by Django 3.0.4 on 2020-03-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20200327_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
