# Generated by Django 2.1.1 on 2019-02-01 16:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('views_amount', models.IntegerField(default=0)),
                ('tags', models.TextField()),
                ('pub_date', models.DateField(default=django.utils.timezone.now)),
                ('reading_time', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'ordering': ['-article_id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=30)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('pub_date', models.DateField(default=datetime.datetime(2019, 2, 1, 16, 14, 39, 752739, tzinfo=utc))),
                ('description', models.TextField()),
                ('article_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='App.Article')),
            ],
            options={
                'ordering': ['-comment_id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('profile_image', models.ImageField(default='furry.jpg', upload_to='')),
                ('profession', models.TextField(default='user')),
                ('user_secret', models.TextField(default='bKcWC6DBhQVhEnVyFh2H3i4o-LUZHzwsWQPpfqY1hs4')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_write_post', 'Can deliver pizzas'),),
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='App.UserProfile'),
        ),
        migrations.AddField(
            model_name='article',
            name='author_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='App.UserProfile'),
        ),
    ]
