# Generated by Django 2.1.1 on 2019-08-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='article_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user_id',
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_image',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_secret',
            field=models.TextField(default='U0atPJVb34lyem7n5G0YdCezqCkMHcWSK77j1srvo0w'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
